"""
Financial health benchmarks and metric mappings configuration.

This module contains benchmark definitions for financial metrics and their
classification into sections for comprehensive financial health analysis.
"""

# Benchmark definitions for financial metrics
# Used to compare actual values and provide insights
BENCHMARKS_INSIGHTS = {
    # 1️⃣ Profitability Analysis
    "Gross Profit Margin": {
        "operator": ">",
        "threshold": 0.35,
        "unit": "%",
        "insight": "Higher margins indicate strong pricing power and product efficiency.",
    },
    "Operating Profit Margin": {
        "operator": ">",
        "threshold": 0.15,
        "unit": "%",
        "insight": "Shows how effectively operations convert revenue into profit.",
    },
    "EBIT Margin": {
        "operator": ">",
        "threshold": 0.15,
        "unit": "%",
        "insight": "Represents profitability before financing and taxes.",
    },
    "EBITDA Margin": {
        "operator": ">",
        "threshold": 0.20,
        "unit": "%",
        "insight": "Indicates core operational profitability before non-cash costs.",
    },
    "Pretax Profit Margin": {
        "operator": ">",
        "threshold": 0.15,
        "unit": "%",
        "insight": "Reflects profitability before tax obligations.",
    },
    "Net Profit Margin": {
        "operator": ">",
        "threshold": 0.10,
        "unit": "%",
        "insight": "Measures total profitability after all expenses.",
    },
    "Return on Assets (ROA)": {
        "operator": ">",
        "threshold": 0.08,
        "unit": "%",
        "insight": "Indicates how efficiently the company uses assets to generate profit.",
    },
    "Return on Equity (ROE)": {
        "operator": ">",
        "threshold": 0.12,
        "unit": "%",
        "insight": "Shows how effectively shareholder equity is utilized for returns.",
    },
    "Return on Invested Capital (ROIC)": {
        "operator": ">",
        "threshold": 0.10,
        "unit": "%",
        "insight": "Higher values mean efficient capital allocation and investment returns.",
    },
    "Return on Capital Employed (ROCE)": {
        "operator": ">",
        "threshold": 0.10,
        "unit": "%",
        "insight": "Measures profitability relative to capital employed.",
    },
    "Earnings Yield": {
        "operator": ">",
        "threshold": 0.05,
        "unit": "%",
        "insight": "Shows earnings relative to stock price; higher yield suggests undervaluation.",
    },
    # 2️⃣ Efficiency & Productivity
    "Fixed Asset Turnover": {
        "operator": ">",
        "threshold": 2.0,
        "unit": "×",
        "insight": "Indicates how effectively fixed assets produce revenue.",
    },
    "Inventory Turnover": {
        "operator": ">",
        "threshold": 8,
        "unit": "×",
        "insight": "Shows how efficiently inventory is sold and replaced.",
    },
    "Receivables Turnover": {
        "operator": "range",
        "low": 5,
        "high": 10,
        "unit": "×",
        "insight": "Evaluates effectiveness in collecting receivables.",
    },
    "Payables Turnover": {
        "operator": "range",
        "low": 3,
        "high": 6,
        "unit": "×",
        "insight": "Measures how quickly payables are settled with suppliers.",
    },
    "Days of Sales Outstanding (DSO)": {
        "operator": "<",
        "threshold": 45,
        "unit": "days",
        "insight": "Lower DSO implies faster collection of receivables.",
    },
    "Days of Inventory Outstanding (DIO)": {
        "operator": "<",
        "threshold": 60,
        "unit": "days",
        "insight": "Shorter DIO means efficient inventory management.",
    },
    "Days of Payables Outstanding (DPO)": {
        "operator": "range",
        "low": 30,
        "high": 60,
        "unit": "days",
        "insight": "Shows payment timing strategy to suppliers.",
    },
    "Operating Cycle": {
        "operator": "<",
        "threshold": 90,
        "unit": "days",
        "insight": "Shorter cycles indicate quicker cash recovery from operations.",
    },
    "Working Capital Turnover": {
        "operator": ">",
        "threshold": 5,
        "unit": "×",
        "insight": "Shows how efficiently working capital is used to drive sales.",
    },
    # 3️⃣ Liquidity & Short-Term Solvency
    "Current Ratio": {
        "operator": "range",
        "low": 1.0,
        "high": 2.0,
        "unit": "",
        "insight": "Measures the ability to meet short-term obligations.",
    },
    "Quick Ratio": {
        "operator": ">=",
        "threshold": 1.0,
        "unit": "",
        "insight": "Excludes inventory to assess true liquidity.",
    },
    "Cash Ratio": {
        "operator": ">=",
        "threshold": 0.2,
        "unit": "",
        "insight": "Higher values mean strong cash reserves.",
    },
    "Working Capital": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Positive working capital shows good short-term health.",
    },
    "Operating Cash Flow Ratio": {
        "operator": ">",
        "threshold": 1.0,
        "unit": "",
        "insight": "Higher ratios indicate healthy cash generation from operations.",
    },
    "Short-term Operating Cash Flow Coverage Ratio": {
        "operator": ">",
        "threshold": 1.0,
        "unit": "",
        "insight": "Shows ability to cover short-term liabilities via operations.",
    },
    # 4️⃣ Leverage & Capital Structure
    "Debt to Assets": {
        "operator": "<",
        "threshold": 0.6,
        "unit": "",
        "insight": "Lower values indicate less leverage and lower financial risk.",
    },
    "Debt to Equity": {
        "operator": "<",
        "threshold": 2.0,
        "unit": "",
        "insight": "Measures reliance on debt financing versus equity.",
    },
    "Debt to Capital": {
        "operator": "<",
        "threshold": 0.5,
        "unit": "",
        "insight": "Shows proportion of capital financed through debt.",
    },
    "Long-Term Debt to Capital": {
        "operator": "<",
        "threshold": 0.4,
        "unit": "",
        "insight": "Assesses long-term leverage sustainability.",
    },
    "Net Debt to EBITDA": {
        "operator": "<",
        "threshold": 3.0,
        "unit": "",
        "insight": "Indicates how many years to repay debt using EBITDA.",
    },
    "Interest Coverage Ratio": {
        "operator": ">",
        "threshold": 3.0,
        "unit": "",
        "insight": "Shows ability to pay interest from operating income.",
    },
    "Debt Service Coverage Ratio": {
        "operator": ">",
        "threshold": 1.5,
        "unit": "",
        "insight": "Higher ratios indicate comfortable debt servicing.",
    },
    "EV / EBITDA": {
        "operator": "<",
        "threshold": 15,
        "unit": "",
        "insight": "Lower values may indicate undervaluation.",
    },
    # 5️⃣ Valuation & Market Multiples
    "Price to Earnings (P/E)": {
        "operator": "range",
        "low": 10,
        "high": 25,
        "unit": "",
        "insight": "Evaluates valuation relative to earnings.",
    },
    "PEG Ratio": {
        "operator": "~",
        "threshold": 1.0,
        "unit": "",
        "insight": "Balances valuation with growth; near 1 is ideal.",
    },
    "Forward PEG Ratio": {
        "operator": "~",
        "threshold": 1.0,
        "unit": "",
        "insight": "Forecasts fair value relative to growth expectations.",
    },
    "Price to Book (P/B)": {
        "operator": "<",
        "threshold": 3.0,
        "unit": "",
        "insight": "Lower ratios suggest undervaluation.",
    },
    "Price to Sales (P/S)": {
        "operator": "<",
        "threshold": 5.0,
        "unit": "",
        "insight": "Assesses valuation based on sales.",
    },
    "Price to Free Cash Flow (P/FCF)": {
        "operator": "<",
        "threshold": 20,
        "unit": "",
        "insight": "Lower ratio means strong cash generation relative to price.",
    },
    "Price to Operating Cash Flow (P/OCF)": {
        "operator": "<",
        "threshold": 15,
        "unit": "",
        "insight": "Indicates how cheap cash flow is priced by investors.",
    },
    "Enterprise Value Multiple": {
        "operator": "<",
        "threshold": 15,
        "unit": "",
        "insight": "Compares valuation to core operating profit.",
    },
    "Price to Fair Value": {
        "operator": "<=",
        "threshold": 1.0,
        "unit": "",
        "insight": "Values below 1 suggest potential undervaluation.",
    },
    "Market Cap": {
        "operator": "custom",
        "unit": "¥",
        "insight": "Indicates company size and investor confidence.",
    },
    "EV to Sales": {
        "operator": "<",
        "threshold": 5.0,
        "unit": "",
        "insight": "Lower values suggest more attractive valuation.",
    },
    # 6️⃣ Cash Flow Strength
    "Operating Cash Flow": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Positive OCF shows healthy core business operations.",
    },
    "Free Cash Flow": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Positive FCF means company generates excess cash after investments.",
    },
    "CapEx to Operating Cash Flow": {
        "operator": "<",
        "threshold": 0.5,
        "unit": "",
        "insight": "Lower ratio implies efficient reinvestment policy.",
    },
    "CapEx to Depreciation": {
        "operator": "range",
        "low": 0.8,
        "high": 1.2,
        "unit": "",
        "insight": "Measures reinvestment adequacy in fixed assets.",
    },
    "Free Cash Flow to Equity": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Positive values indicate potential for dividends or buybacks.",
    },
    "Free Cash Flow Yield": {
        "operator": ">",
        "threshold": 0.05,
        "unit": "%",
        "insight": "Shows return of free cash flow relative to market cap.",
    },
    # 7️⃣ Asset Quality & Capital Efficiency
    "Tangible Asset Value": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Higher tangible assets imply strong collateral and asset base.",
    },
    "Intangibles to Total Assets": {
        "operator": "<",
        "threshold": 0.4,
        "unit": "",
        "insight": "Lower ratios mean more stable asset quality.",
    },
    "Invested Capital": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Represents total long-term investments for returns.",
    },
    "Return on Tangible Assets": {
        "operator": ">",
        "threshold": 0.08,
        "unit": "%",
        "insight": "Indicates profit efficiency based on tangible asset base.",
    },
    "Working Capital / Net Current Asset Value": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Positive working capital reflects short-term stability.",
    },
    # 8️⃣ Dividend & Shareholder Returns
    "Dividend Yield": {
        "operator": ">",
        "threshold": 0.02,
        "unit": "%",
        "insight": "Measures cash return to shareholders.",
    },
    "Dividend Payout Ratio": {
        "operator": "range",
        "low": 0.30,
        "high": 0.60,
        "unit": "%",
        "insight": "Indicates dividend sustainability.",
    },
    "Dividend Yield Percentage": {
        "operator": ">",
        "threshold": 0.02,
        "unit": "%",
        "insight": "Higher yield attracts income investors.",
    },
    "Free Cash Flow to Dividend Coverage": {
        "operator": ">",
        "threshold": 1.0,
        "unit": "",
        "insight": "Shows whether FCF sufficiently covers dividend payouts.",
    },
    # 9️⃣ Per-Share Performance
    "Revenue per Share": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Higher values indicate sales growth per share.",
    },
    "Earnings Per Share (EPS)": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Shows profitability on a per-share basis.",
    },
    "Book Value per Share": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Represents underlying asset value per share.",
    },
    "Tangible Book Value per Share": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Excludes intangibles to show real asset backing.",
    },
    "Operating Cash Flow per Share": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Reflects cash generation per share.",
    },
    "Free Cash Flow per Share": {
        "operator": ">",
        "threshold": 0,
        "unit": "",
        "insight": "Shows cash available for dividends and reinvestment.",
    },
    # 🔟 Tax & Cost Structure Analysis
    "Effective Tax Rate": {
        "operator": "range",
        "low": 0.20,
        "high": 0.35,
        "unit": "%",
        "insight": "Indicates tax efficiency relative to income.",
    },
    "Tax Burden": {
        "operator": ">",
        "threshold": 0.7,
        "unit": "",
        "insight": "Higher burden ratio means lower tax impact on net income.",
    },
    "Interest Burden": {
        "operator": ">",
        "threshold": 0.7,
        "unit": "",
        "insight": "Shows impact of interest expenses on profit.",
    },
    "SG&A to Revenue": {
        "operator": "<",
        "threshold": 0.25,
        "unit": "%",
        "insight": "Lower ratio suggests efficient cost control.",
    },
    "R&D to Revenue": {
        "operator": "range",
        "low": 0.03,
        "high": 0.10,
        "unit": "%",
        "insight": "Optimal range reflects balanced innovation spending.",
    },
    "Stock-Based Compensation to Revenue": {
        "operator": "<",
        "threshold": 0.005,
        "unit": "%",
        "insight": "Lower ratio indicates less shareholder dilution.",
    },
}


# Section to metric mapping
# Groups related financial metrics into sections for easier analysis
SECTION_METRIC_MAP = {
    "Profitability Analysis": [
        ("Gross Profit Margin", "gross_profit_margin"),
        ("Operating Profit Margin", "operating_profit_margin"),
        ("EBIT Margin", "ebit_margin"),
        ("EBITDA Margin", "ebitda_margin"),
        ("Pretax Profit Margin", "pretax_profit_margin"),
        ("Net Profit Margin", "net_profit_margin"),
        ("Return on Assets (ROA)", "return_on_assets"),
        ("Return on Equity (ROE)", "return_on_equity"),
        ("Return on Invested Capital (ROIC)", "return_on_invested_capital"),
        ("Return on Capital Employed (ROCE)", "return_on_capital_employed"),
        ("Earnings Yield", "earnings_yield"),
    ],
    "Efficiency and Productivity Analysis": [
        ("Asset Turnover", "asset_turnover"),
        ("Fixed Asset Turnover", "fixed_asset_turnover"),
        ("Inventory Turnover", "inventory_turnover"),
        ("Receivables Turnover", "receivables_turnover"),
        ("Payables Turnover", "payables_turnover"),
        ("Days of Sales Outstanding (DSO)", "days_of_sales_outstanding"),
        ("Days of Inventory Outstanding (DIO)", "days_of_inventory_outstanding"),
        ("Days of Payables Outstanding (DPO)", "days_of_payables_outstanding"),
        ("Operating Cycle", "operating_cycle"),
        ("Cash Conversion Cycle", "cash_conversion_cycle"),
        ("Working Capital Turnover", "working_capital_turnover_ratio"),
    ],
    "Liquidity and Short-Term Solvency": [
        ("Current Ratio", "current_ratio"),
        ("Quick Ratio", "quick_ratio"),
        ("Cash Ratio", "cash_ratio"),
        ("Working Capital", "working_capital"),
        ("Operating Cash Flow Ratio", "operating_cash_flow_ratio"),
        (
            "Short-term Operating Cash Flow Coverage Ratio",
            "short_term_operating_cash_flow_coverage_ratio",
        ),
    ],
    "Leverage and Capital Structure": [
        ("Debt to Assets", "debt_to_assets_ratio"),
        ("Debt to Equity", "debt_to_equity_ratio"),
        ("Debt to Capital", "debt_to_capital_ratio"),
        ("Long-Term Debt to Capital", "long_term_debt_to_capital_ratio"),
        ("Financial Leverage Ratio", "financial_leverage_ratio"),
        ("Net Debt to EBITDA", "net_debt_to_ebitda"),
        ("Interest Coverage Ratio", "interest_coverage_ratio"),
        ("Debt Service Coverage Ratio", "debt_service_coverage_ratio"),
        ("Enterprise Value (EV)", "enterprise_value"),
        ("EV / EBITDA", "ev_to_ebitda"),
    ],
    "Valuation and Market Multiples": [
        ("Price to Earnings (P/E)", "price_to_earnings_ratio"),
        ("PEG Ratio", "price_to_earnings_growth_ratio"),
        ("Forward PEG Ratio", "forward_price_to_earnings_growth_ratio"),
        ("Price to Book (P/B)", "price_to_book_ratio"),
        ("Price to Sales (P/S)", "price_to_sales_ratio"),
        ("Price to Free Cash Flow (P/FCF)", "price_to_free_cash_flow_ratio"),
        ("Price to Operating Cash Flow (P/OCF)", "price_to_operating_cash_flow_ratio"),
        ("Enterprise Value Multiple", "enterprise_value_multiple"),
        ("Price to Fair Value", "price_to_fair_value"),
        ("Market Cap", "market_cap"),
        ("EV to Sales", "ev_to_sales"),
    ],
    "Cash Flow Strength": [
        ("Operating Cash Flow Ratio", "operating_cash_flow_ratio"),
        ("Free Cash Flow", "free_cash_flow_to_firm"),
        ("Free Cash Flow to Equity", "free_cash_flow_to_equity"),
        ("CapEx to Operating Cash Flow", "capex_to_operating_cash_flow"),
        ("CapEx to Depreciation", "capex_to_depreciation"),
        ("Free Cash Flow Yield", "free_cash_flow_yield"),
        ("Dividend & CapEx Coverage", "dividend_paid_and_capex_coverage_ratio"),
        (
            "Free Cash Flow Operating Cash Flow Ratio",
            "free_cash_flow_operating_cash_flow_ratio",
        ),
    ],
    "Asset Quality and Capital Efficiency": [
        ("Tangible Asset Value", "tangible_asset_value"),
        ("Intangibles to Total Assets", "intangibles_to_total_assets"),
        ("Invested Capital", "invested_capital"),
        ("Return on Tangible Assets", "return_on_tangible_assets"),
        ("Working Capital", "working_capital"),
        ("Net Current Asset Value", "net_current_asset_value"),
        ("Income Quality", "income_quality"),
    ],
    "Dividend and Shareholder Returns": [
        ("Dividend Yield", "dividend_yield"),
        ("Dividend Payout Ratio", "dividend_payout_ratio"),
        ("Dividend Yield Percentage", "dividend_yield_percentage"),
        (
            "Free Cash Flow to Dividend Coverage",
            "dividend_paid_and_capex_coverage_ratio",
        ),
        ("Dividend Paid & CapEx Coverage", "dividend_paid_and_capex_coverage_ratio"),
    ],
    "Per Share Performance": [
        ("Revenue per Share", "revenue_per_share"),
        ("Earnings Per Share (EPS)", "net_income_per_share"),
        ("Book Value per Share", "book_value_per_share"),
        ("Tangible Book Value per Share", "tangible_book_value_per_share"),
        ("Operating Cash Flow per Share", "operating_cash_flow_per_share"),
        ("Free Cash Flow per Share", "free_cash_flow_per_share"),
        ("CapEx per Share", "capex_per_share"),
        ("Shareholders’ Equity per Share", "shareholders_equity_per_share"),
    ],
    "Tax and Cost Structure Analysis": [
        ("Effective Tax Rate", "effective_tax_rate"),
        ("Tax Burden", "tax_burden"),
        ("Interest Burden", "interest_burden"),
        ("SG&A to Revenue", "sales_general_and_administrative_to_revenue"),
        ("R&D to Revenue", "research_and_development_to_revenue"),
        ("Stock-Based Compensation to Revenue", "stock_based_compensation_to_revenue"),
    ],
}
