"""Initial commit

Revision ID: 1c3ab513a67c
Revises: 
Create Date: 2025-11-07 20:17:42.684390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3ab513a67c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=250), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('exchange_full_name', sa.String(length=250), nullable=False),
    sa.Column('exchange', sa.String(length=250), nullable=False),
    sa.Column('industry', sa.String(length=250), nullable=True),
    sa.Column('sector', sa.String(length=250), nullable=True),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_exchange'), 'companies', ['exchange'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_index('ix_company_sector_industry', 'companies', ['sector', 'industry'], unique=False)
    op.create_index('ix_company_symbol_exchange', 'companies', ['symbol', 'exchange'], unique=False)
    op.create_table('company_dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('declaration_date', sa.Date(), nullable=True),
    sa.Column('adj_dividend', sa.Float(), nullable=True),
    sa.Column('dividend', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_dividend_date')
    )
    op.create_index(op.f('ix_company_dividends_id'), 'company_dividends', ['id'], unique=False)
    op.create_index(op.f('ix_company_dividends_symbol'), 'company_dividends', ['symbol'], unique=False)
    op.create_index('ix_dividend_symbol_date', 'company_dividends', ['symbol', 'date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theme_preference', sa.String(length=20), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('company_analyst_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('revenue_low', sa.Float(), nullable=True),
    sa.Column('revenue_high', sa.Float(), nullable=True),
    sa.Column('revenue_avg', sa.Float(), nullable=True),
    sa.Column('ebitda_low', sa.Float(), nullable=True),
    sa.Column('ebitda_high', sa.Float(), nullable=True),
    sa.Column('ebitda_avg', sa.Float(), nullable=True),
    sa.Column('ebit_low', sa.Float(), nullable=True),
    sa.Column('ebit_high', sa.Float(), nullable=True),
    sa.Column('ebit_avg', sa.Float(), nullable=True),
    sa.Column('net_income_low', sa.Float(), nullable=True),
    sa.Column('net_income_high', sa.Float(), nullable=True),
    sa.Column('net_income_avg', sa.Float(), nullable=True),
    sa.Column('sga_expense_low', sa.Float(), nullable=True),
    sa.Column('sga_expense_high', sa.Float(), nullable=True),
    sa.Column('sga_expense_avg', sa.Float(), nullable=True),
    sa.Column('eps_avg', sa.Float(), nullable=True),
    sa.Column('eps_high', sa.Float(), nullable=True),
    sa.Column('eps_low', sa.Float(), nullable=True),
    sa.Column('num_analysts_revenue', sa.Integer(), nullable=True),
    sa.Column('num_analysts_eps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_analyst_estimate_date')
    )
    op.create_index(op.f('ix_company_analyst_estimates_company_id'), 'company_analyst_estimates', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_analyst_estimates_id'), 'company_analyst_estimates', ['id'], unique=False)
    op.create_index(op.f('ix_company_analyst_estimates_symbol'), 'company_analyst_estimates', ['symbol'], unique=False)
    op.create_index('ix_estimate_symbol_date', 'company_analyst_estimates', ['symbol', 'date'], unique=False)
    op.create_table('company_balance_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('accepted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True),
    sa.Column('short_term_investments', sa.Float(), nullable=True),
    sa.Column('cash_and_short_term_investments', sa.Float(), nullable=True),
    sa.Column('net_receivables', sa.Float(), nullable=True),
    sa.Column('accounts_receivables', sa.Float(), nullable=True),
    sa.Column('other_receivables', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('prepaids', sa.Float(), nullable=True),
    sa.Column('other_current_assets', sa.Float(), nullable=True),
    sa.Column('total_current_assets', sa.Float(), nullable=True),
    sa.Column('property_plant_equipment_net', sa.Float(), nullable=True),
    sa.Column('goodwill', sa.Float(), nullable=True),
    sa.Column('intangible_assets', sa.Float(), nullable=True),
    sa.Column('goodwill_and_intangible_assets', sa.Float(), nullable=True),
    sa.Column('long_term_investments', sa.Float(), nullable=True),
    sa.Column('tax_assets', sa.Float(), nullable=True),
    sa.Column('other_non_current_assets', sa.Float(), nullable=True),
    sa.Column('total_non_current_assets', sa.Float(), nullable=True),
    sa.Column('other_assets', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_payables', sa.Float(), nullable=True),
    sa.Column('account_payables', sa.Float(), nullable=True),
    sa.Column('other_payables', sa.Float(), nullable=True),
    sa.Column('accrued_expenses', sa.Float(), nullable=True),
    sa.Column('short_term_debt', sa.Float(), nullable=True),
    sa.Column('capital_lease_obligations_current', sa.Float(), nullable=True),
    sa.Column('tax_payables', sa.Float(), nullable=True),
    sa.Column('deferred_revenue', sa.Float(), nullable=True),
    sa.Column('other_current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_current_liabilities', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('deferred_revenue_non_current', sa.Float(), nullable=True),
    sa.Column('deferred_tax_liabilities_non_current', sa.Float(), nullable=True),
    sa.Column('other_non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('other_liabilities', sa.Float(), nullable=True),
    sa.Column('capital_lease_obligations', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('treasury_stock', sa.Float(), nullable=True),
    sa.Column('preferred_stock', sa.Float(), nullable=True),
    sa.Column('common_stock', sa.Float(), nullable=True),
    sa.Column('retained_earnings', sa.Float(), nullable=True),
    sa.Column('additional_paid_in_capital', sa.Float(), nullable=True),
    sa.Column('accumulated_other_comprehensive_income_loss', sa.Float(), nullable=True),
    sa.Column('other_total_stockholders_equity', sa.Float(), nullable=True),
    sa.Column('total_stockholders_equity', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('minority_interest', sa.Float(), nullable=True),
    sa.Column('total_liabilities_and_total_equity', sa.Float(), nullable=True),
    sa.Column('total_investments', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('net_debt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period', name='uq_balance_sheet_period')
    )
    op.create_index('ix_balance_sheet_fiscal_year', 'company_balance_sheets', ['fiscal_year'], unique=False)
    op.create_index('ix_balance_sheet_symbol_date', 'company_balance_sheets', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_company_balance_sheets_company_id'), 'company_balance_sheets', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_balance_sheets_fiscal_year'), 'company_balance_sheets', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_company_balance_sheets_symbol'), 'company_balance_sheets', ['symbol'], unique=False)
    op.create_table('company_cash_flow_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('accepted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Float(), nullable=True),
    sa.Column('deferred_income_tax', sa.Float(), nullable=True),
    sa.Column('stock_based_compensation', sa.Float(), nullable=True),
    sa.Column('change_in_working_capital', sa.Float(), nullable=True),
    sa.Column('accounts_receivables', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('accounts_payables', sa.Float(), nullable=True),
    sa.Column('other_working_capital', sa.Float(), nullable=True),
    sa.Column('other_non_cash_items', sa.Float(), nullable=True),
    sa.Column('net_cash_provided_by_operating_activities', sa.Float(), nullable=True),
    sa.Column('investments_in_property_plant_and_equipment', sa.Float(), nullable=True),
    sa.Column('acquisitions_net', sa.Float(), nullable=True),
    sa.Column('purchases_of_investments', sa.Float(), nullable=True),
    sa.Column('sales_maturities_of_investments', sa.Float(), nullable=True),
    sa.Column('other_investing_activities', sa.Float(), nullable=True),
    sa.Column('net_cash_provided_by_investing_activities', sa.Float(), nullable=True),
    sa.Column('net_debt_issuance', sa.Float(), nullable=True),
    sa.Column('long_term_net_debt_issuance', sa.Float(), nullable=True),
    sa.Column('short_term_net_debt_issuance', sa.Float(), nullable=True),
    sa.Column('net_stock_issuance', sa.Float(), nullable=True),
    sa.Column('net_common_stock_issuance', sa.Float(), nullable=True),
    sa.Column('common_stock_issuance', sa.Float(), nullable=True),
    sa.Column('common_stock_repurchased', sa.Float(), nullable=True),
    sa.Column('net_preferred_stock_issuance', sa.Float(), nullable=True),
    sa.Column('net_dividends_paid', sa.Float(), nullable=True),
    sa.Column('common_dividends_paid', sa.Float(), nullable=True),
    sa.Column('preferred_dividends_paid', sa.Float(), nullable=True),
    sa.Column('other_financing_activities', sa.Float(), nullable=True),
    sa.Column('net_cash_provided_by_financing_activities', sa.Float(), nullable=True),
    sa.Column('effect_of_forex_changes_on_cash', sa.Float(), nullable=True),
    sa.Column('net_change_in_cash', sa.Float(), nullable=True),
    sa.Column('cash_at_end_of_period', sa.Float(), nullable=True),
    sa.Column('cash_at_beginning_of_period', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('capital_expenditure', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('income_taxes_paid', sa.Float(), nullable=True),
    sa.Column('interest_paid', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period', name='uq_cashflow_period')
    )
    op.create_index('ix_cashflow_fiscal_year', 'company_cash_flow_statements', ['fiscal_year'], unique=False)
    op.create_index('ix_cashflow_symbol_date', 'company_cash_flow_statements', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_company_cash_flow_statements_company_id'), 'company_cash_flow_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_cash_flow_statements_fiscal_year'), 'company_cash_flow_statements', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_company_cash_flow_statements_symbol'), 'company_cash_flow_statements', ['symbol'], unique=False)
    op.create_table('company_dcf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('dcf', sa.Float(), nullable=True),
    sa.Column('stock_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_dcf_company')
    )
    op.create_index(op.f('ix_company_dcf_company_id'), 'company_dcf', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_dcf_id'), 'company_dcf', ['id'], unique=False)
    op.create_index(op.f('ix_company_dcf_symbol'), 'company_dcf', ['symbol'], unique=False)
    op.create_index('ix_dcf_symbol_date', 'company_dcf', ['symbol', 'date'], unique=False)
    op.create_table('company_financial_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('benchmark', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'section', 'metric', name='uq_health_metric')
    )
    op.create_index(op.f('ix_company_financial_health_company_id'), 'company_financial_health', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_financial_health_symbol'), 'company_financial_health', ['symbol'], unique=False)
    op.create_index('ix_health_symbol_section', 'company_financial_health', ['symbol', 'section'], unique=False)
    op.create_table('company_financial_ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('gross_profit_margin', sa.Float(), nullable=True),
    sa.Column('ebit_margin', sa.Float(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('operating_profit_margin', sa.Float(), nullable=True),
    sa.Column('pretax_profit_margin', sa.Float(), nullable=True),
    sa.Column('continuous_operations_profit_margin', sa.Float(), nullable=True),
    sa.Column('net_profit_margin', sa.Float(), nullable=True),
    sa.Column('bottom_line_profit_margin', sa.Float(), nullable=True),
    sa.Column('receivables_turnover', sa.Float(), nullable=True),
    sa.Column('payables_turnover', sa.Float(), nullable=True),
    sa.Column('inventory_turnover', sa.Float(), nullable=True),
    sa.Column('fixed_asset_turnover', sa.Float(), nullable=True),
    sa.Column('asset_turnover', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('solvency_ratio', sa.Float(), nullable=True),
    sa.Column('cash_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_earnings_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_earnings_growth_ratio', sa.Float(), nullable=True),
    sa.Column('forward_price_to_earnings_growth_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_book_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_sales_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_free_cash_flow_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_operating_cash_flow_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_assets_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_capital_ratio', sa.Float(), nullable=True),
    sa.Column('long_term_debt_to_capital_ratio', sa.Float(), nullable=True),
    sa.Column('financial_leverage_ratio', sa.Float(), nullable=True),
    sa.Column('working_capital_turnover_ratio', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow_ratio', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow_sales_ratio', sa.Float(), nullable=True),
    sa.Column('free_cash_flow_operating_cash_flow_ratio', sa.Float(), nullable=True),
    sa.Column('debt_service_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('interest_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('short_term_operating_cash_flow_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('capital_expenditure_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_paid_and_capex_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_payout_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('dividend_yield_percentage', sa.Float(), nullable=True),
    sa.Column('revenue_per_share', sa.Float(), nullable=True),
    sa.Column('net_income_per_share', sa.Float(), nullable=True),
    sa.Column('interest_debt_per_share', sa.Float(), nullable=True),
    sa.Column('cash_per_share', sa.Float(), nullable=True),
    sa.Column('book_value_per_share', sa.Float(), nullable=True),
    sa.Column('tangible_book_value_per_share', sa.Float(), nullable=True),
    sa.Column('shareholders_equity_per_share', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow_per_share', sa.Float(), nullable=True),
    sa.Column('capex_per_share', sa.Float(), nullable=True),
    sa.Column('free_cash_flow_per_share', sa.Float(), nullable=True),
    sa.Column('net_income_per_ebt', sa.Float(), nullable=True),
    sa.Column('ebt_per_ebit', sa.Float(), nullable=True),
    sa.Column('price_to_fair_value', sa.Float(), nullable=True),
    sa.Column('debt_to_market_cap', sa.Float(), nullable=True),
    sa.Column('effective_tax_rate', sa.Float(), nullable=True),
    sa.Column('enterprise_value_multiple', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period', name='uq_ratio_period')
    )
    op.create_index(op.f('ix_company_financial_ratios_company_id'), 'company_financial_ratios', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_financial_ratios_fiscal_year'), 'company_financial_ratios', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_company_financial_ratios_id'), 'company_financial_ratios', ['id'], unique=False)
    op.create_index(op.f('ix_company_financial_ratios_symbol'), 'company_financial_ratios', ['symbol'], unique=False)
    op.create_index('ix_ratio_fiscal_year', 'company_financial_ratios', ['fiscal_year'], unique=False)
    op.create_index('ix_ratio_symbol_date', 'company_financial_ratios', ['symbol', 'date'], unique=False)
    op.create_table('company_financial_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('altman_z_score', sa.Float(), nullable=True),
    sa.Column('piotroski_score', sa.Integer(), nullable=True),
    sa.Column('working_capital', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('retained_earnings', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_financial_score_company')
    )
    op.create_index(op.f('ix_company_financial_scores_company_id'), 'company_financial_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_financial_scores_id'), 'company_financial_scores', ['id'], unique=False)
    op.create_index(op.f('ix_company_financial_scores_symbol'), 'company_financial_scores', ['symbol'], unique=False)
    op.create_index('ix_score_symbol', 'company_financial_scores', ['symbol'], unique=False)
    op.create_table('company_general_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('news_title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('news_url', sa.String(length=1000), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'news_title', name='uq_general_news_title')
    )
    op.create_index(op.f('ix_company_general_news_company_id'), 'company_general_news', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_general_news_id'), 'company_general_news', ['id'], unique=False)
    op.create_index(op.f('ix_company_general_news_symbol'), 'company_general_news', ['symbol'], unique=False)
    op.create_index('ix_general_news_symbol_date', 'company_general_news', ['symbol', 'published_date'], unique=False)
    op.create_table('company_grading_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('news_url', sa.String(length=1000), nullable=False),
    sa.Column('news_title', sa.String(length=500), nullable=False),
    sa.Column('news_base_url', sa.String(length=500), nullable=True),
    sa.Column('news_publisher', sa.String(length=255), nullable=True),
    sa.Column('new_grade', sa.String(length=10), nullable=False),
    sa.Column('previous_grade', sa.String(length=10), nullable=True),
    sa.Column('grading_company', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('price_when_posted', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'news_title', 'grading_company', name='uq_grading_news')
    )
    op.create_index(op.f('ix_company_grading_news_company_id'), 'company_grading_news', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_grading_news_id'), 'company_grading_news', ['id'], unique=False)
    op.create_index(op.f('ix_company_grading_news_symbol'), 'company_grading_news', ['symbol'], unique=False)
    op.create_index('ix_grading_news_symbol_date', 'company_grading_news', ['symbol', 'published_date'], unique=False)
    op.create_table('company_grading_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('sell', sa.Integer(), nullable=False),
    sa.Column('strong_sell', sa.Integer(), nullable=False),
    sa.Column('consensus', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_grading_summary_company')
    )
    op.create_index(op.f('ix_company_grading_summaries_id'), 'company_grading_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_company_grading_summaries_symbol'), 'company_grading_summaries', ['symbol'], unique=False)
    op.create_index('ix_grading_summary_symbol', 'company_grading_summaries', ['symbol'], unique=False)
    op.create_table('company_gradings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('grading_company', sa.String(length=255), nullable=True),
    sa.Column('previous_grade', sa.String(length=50), nullable=True),
    sa.Column('new_grade', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_gradings_company_id'), 'company_gradings', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_gradings_id'), 'company_gradings', ['id'], unique=False)
    op.create_index(op.f('ix_company_gradings_symbol'), 'company_gradings', ['symbol'], unique=False)
    op.create_index('ix_grading_symbol_date', 'company_gradings', ['symbol', 'date'], unique=False)
    op.create_table('company_income_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('accepted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('research_and_development_expenses', sa.Float(), nullable=True),
    sa.Column('general_and_administrative_expenses', sa.Float(), nullable=True),
    sa.Column('selling_and_marketing_expenses', sa.Float(), nullable=True),
    sa.Column('selling_general_and_administrative_expenses', sa.Float(), nullable=True),
    sa.Column('other_expenses', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('cost_and_expenses', sa.Float(), nullable=True),
    sa.Column('net_interest_income', sa.Float(), nullable=True),
    sa.Column('interest_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('non_operating_income_excluding_interest', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('total_other_income_expenses_net', sa.Float(), nullable=True),
    sa.Column('income_before_tax', sa.Float(), nullable=True),
    sa.Column('income_tax_expense', sa.Float(), nullable=True),
    sa.Column('net_income_from_continuing_operations', sa.Float(), nullable=True),
    sa.Column('net_income_from_discontinued_operations', sa.Float(), nullable=True),
    sa.Column('other_adjustments_to_net_income', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('net_income_deductions', sa.Float(), nullable=True),
    sa.Column('bottom_line_net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('weighted_average_shs_out', sa.Float(), nullable=True),
    sa.Column('weighted_average_shs_out_dil', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period', name='uq_income_period')
    )
    op.create_index(op.f('ix_company_income_statements_company_id'), 'company_income_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_income_statements_fiscal_year'), 'company_income_statements', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_company_income_statements_id'), 'company_income_statements', ['id'], unique=False)
    op.create_index(op.f('ix_company_income_statements_symbol'), 'company_income_statements', ['symbol'], unique=False)
    op.create_index('ix_income_fiscal_year', 'company_income_statements', ['fiscal_year'], unique=False)
    op.create_index('ix_income_symbol_date', 'company_income_statements', ['symbol', 'date'], unique=False)
    op.create_table('company_key_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('ev_to_sales', sa.Float(), nullable=True),
    sa.Column('ev_to_operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('ev_to_free_cash_flow', sa.Float(), nullable=True),
    sa.Column('ev_to_ebitda', sa.Float(), nullable=True),
    sa.Column('net_debt_to_ebitda', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('income_quality', sa.Float(), nullable=True),
    sa.Column('graham_number', sa.Float(), nullable=True),
    sa.Column('graham_net_net', sa.Float(), nullable=True),
    sa.Column('tax_burden', sa.Float(), nullable=True),
    sa.Column('interest_burden', sa.Float(), nullable=True),
    sa.Column('working_capital', sa.Float(), nullable=True),
    sa.Column('invested_capital', sa.Float(), nullable=True),
    sa.Column('return_on_assets', sa.Float(), nullable=True),
    sa.Column('operating_return_on_assets', sa.Float(), nullable=True),
    sa.Column('return_on_tangible_assets', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('return_on_invested_capital', sa.Float(), nullable=True),
    sa.Column('return_on_capital_employed', sa.Float(), nullable=True),
    sa.Column('earnings_yield', sa.Float(), nullable=True),
    sa.Column('free_cash_flow_yield', sa.Float(), nullable=True),
    sa.Column('capex_to_operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('capex_to_depreciation', sa.Float(), nullable=True),
    sa.Column('capex_to_revenue', sa.Float(), nullable=True),
    sa.Column('sales_general_and_administrative_to_revenue', sa.Float(), nullable=True),
    sa.Column('research_and_development_to_revenue', sa.Float(), nullable=True),
    sa.Column('stock_based_compensation_to_revenue', sa.Float(), nullable=True),
    sa.Column('intangibles_to_total_assets', sa.Float(), nullable=True),
    sa.Column('average_receivables', sa.Float(), nullable=True),
    sa.Column('average_payables', sa.Float(), nullable=True),
    sa.Column('average_inventory', sa.Float(), nullable=True),
    sa.Column('days_of_sales_outstanding', sa.Float(), nullable=True),
    sa.Column('days_of_payables_outstanding', sa.Float(), nullable=True),
    sa.Column('days_of_inventory_outstanding', sa.Float(), nullable=True),
    sa.Column('operating_cycle', sa.Float(), nullable=True),
    sa.Column('cash_conversion_cycle', sa.Float(), nullable=True),
    sa.Column('free_cash_flow_to_equity', sa.Float(), nullable=True),
    sa.Column('free_cash_flow_to_firm', sa.Float(), nullable=True),
    sa.Column('tangible_asset_value', sa.Float(), nullable=True),
    sa.Column('net_current_asset_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period', name='uq_metrics_period')
    )
    op.create_index(op.f('ix_company_key_metrics_company_id'), 'company_key_metrics', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_key_metrics_fiscal_year'), 'company_key_metrics', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_company_key_metrics_id'), 'company_key_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_company_key_metrics_symbol'), 'company_key_metrics', ['symbol'], unique=False)
    op.create_index('ix_metrics_fiscal_year', 'company_key_metrics', ['fiscal_year'], unique=False)
    op.create_index('ix_metrics_symbol_date', 'company_key_metrics', ['symbol', 'date'], unique=False)
    op.create_table('company_price_target_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('news_url', sa.String(length=1000), nullable=False),
    sa.Column('news_title', sa.String(length=500), nullable=False),
    sa.Column('analyst_name', sa.String(length=255), nullable=False),
    sa.Column('price_target', sa.Float(), nullable=False),
    sa.Column('adj_price_target', sa.Float(), nullable=True),
    sa.Column('price_when_posted', sa.Float(), nullable=False),
    sa.Column('news_publisher', sa.String(length=255), nullable=True),
    sa.Column('news_base_url', sa.String(length=500), nullable=True),
    sa.Column('analyst_company', sa.String(length=255), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'news_title', 'analyst_name', name='uq_price_target_news')
    )
    op.create_index(op.f('ix_company_price_target_news_id'), 'company_price_target_news', ['id'], unique=False)
    op.create_index(op.f('ix_company_price_target_news_symbol'), 'company_price_target_news', ['symbol'], unique=False)
    op.create_index('ix_price_target_news_symbol_date', 'company_price_target_news', ['symbol', 'published_date'], unique=False)
    op.create_table('company_price_target_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('last_month_count', sa.Integer(), nullable=False),
    sa.Column('last_month_average_price_target', sa.Float(), nullable=False),
    sa.Column('last_quarter_count', sa.Integer(), nullable=False),
    sa.Column('last_quarter_average_price_target', sa.Float(), nullable=False),
    sa.Column('last_year_count', sa.Integer(), nullable=False),
    sa.Column('last_year_average_price_target', sa.Float(), nullable=False),
    sa.Column('all_time_count', sa.Integer(), nullable=False),
    sa.Column('all_time_average_price_target', sa.Float(), nullable=False),
    sa.Column('publishers', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_price_target_summary_company')
    )
    op.create_index(op.f('ix_company_price_target_summaries_company_id'), 'company_price_target_summaries', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_price_target_summaries_id'), 'company_price_target_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_company_price_target_summaries_symbol'), 'company_price_target_summaries', ['symbol'], unique=False)
    op.create_index('ix_price_target_summary_symbol', 'company_price_target_summaries', ['symbol'], unique=False)
    op.create_table('company_price_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('target_high', sa.Float(), nullable=True),
    sa.Column('target_low', sa.Float(), nullable=True),
    sa.Column('target_consensus', sa.Float(), nullable=True),
    sa.Column('target_median', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_price_target_company')
    )
    op.create_index(op.f('ix_company_price_targets_company_id'), 'company_price_targets', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_price_targets_id'), 'company_price_targets', ['id'], unique=False)
    op.create_index(op.f('ix_company_price_targets_symbol'), 'company_price_targets', ['symbol'], unique=False)
    op.create_table('company_rating_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('discounted_cash_flow_score', sa.Integer(), nullable=True),
    sa.Column('return_on_equity_score', sa.Integer(), nullable=True),
    sa.Column('return_on_assets_score', sa.Integer(), nullable=True),
    sa.Column('debt_to_equity_score', sa.Integer(), nullable=True),
    sa.Column('price_to_earnings_score', sa.Integer(), nullable=True),
    sa.Column('price_to_book_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_rating_summary_company')
    )
    op.create_index(op.f('ix_company_rating_summaries_company_id'), 'company_rating_summaries', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_rating_summaries_id'), 'company_rating_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_company_rating_summaries_symbol'), 'company_rating_summaries', ['symbol'], unique=False)
    op.create_index('ix_rating_summary_symbol', 'company_rating_summaries', ['symbol'], unique=False)
    op.create_table('company_revenue_product_segmentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('segments_data', sa.Text(), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'fiscal_year', 'period', name='uq_revenue_segment')
    )
    op.create_index(op.f('ix_company_revenue_product_segmentations_company_id'), 'company_revenue_product_segmentations', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_revenue_product_segmentations_id'), 'company_revenue_product_segmentations', ['id'], unique=False)
    op.create_index(op.f('ix_company_revenue_product_segmentations_symbol'), 'company_revenue_product_segmentations', ['symbol'], unique=False)
    op.create_index('ix_segment_symbol_year', 'company_revenue_product_segmentations', ['symbol', 'fiscal_year'], unique=False)
    op.create_table('company_stock_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('news_title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('news_url', sa.String(length=1000), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'news_title', name='uq_stock_news_title')
    )
    op.create_index(op.f('ix_company_stock_news_company_id'), 'company_stock_news', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_stock_news_id'), 'company_stock_news', ['id'], unique=False)
    op.create_index(op.f('ix_company_stock_news_symbol'), 'company_stock_news', ['symbol'], unique=False)
    op.create_index('ix_stock_news_symbol_date', 'company_stock_news', ['symbol', 'published_date'], unique=False)
    op.create_table('company_stock_peers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'symbol', name='uq_stock_peer_company_symbol')
    )
    op.create_index(op.f('ix_company_stock_peers_company_id'), 'company_stock_peers', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_stock_peers_symbol'), 'company_stock_peers', ['symbol'], unique=False)
    op.create_index('ix_stock_peer_symbol', 'company_stock_peers', ['symbol'], unique=False)
    op.create_table('company_stock_splits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('numerator', sa.Integer(), nullable=False),
    sa.Column('denominator', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_stock_split_company_date')
    )
    op.create_index(op.f('ix_company_stock_splits_company_id'), 'company_stock_splits', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_stock_splits_symbol'), 'company_stock_splits', ['symbol'], unique=False)
    op.create_index('ix_stock_split_symbol_date', 'company_stock_splits', ['symbol', 'date'], unique=False)
    op.create_table('company_technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('simple_moving_average', sa.Float(), nullable=True),
    sa.Column('exponential_moving_average', sa.Float(), nullable=True),
    sa.Column('weighted_moving_average', sa.Float(), nullable=True),
    sa.Column('double_exponential_moving_average', sa.Float(), nullable=True),
    sa.Column('triple_exponential_moving_average', sa.Float(), nullable=True),
    sa.Column('relative_strength_index', sa.Float(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.Column('williams_percent_r', sa.Float(), nullable=True),
    sa.Column('average_directional_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_technical_indicator_company_date')
    )
    op.create_index(op.f('ix_company_technical_indicators_company_id'), 'company_technical_indicators', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_technical_indicators_symbol'), 'company_technical_indicators', ['symbol'], unique=False)
    op.create_index('ix_technical_indicator_symbol_date', 'company_technical_indicators', ['symbol', 'date'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('portfolio_alerts', sa.Boolean(), nullable=False),
    sa.Column('price_alerts', sa.Boolean(), nullable=False),
    sa.Column('daily_news_digest', sa.Boolean(), nullable=False),
    sa.Column('weekly_report', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_category', 'notifications', ['category'], unique=False)
    op.create_index('ix_notification_user_date', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', name='currency'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('stock_price_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('one_day', sa.Float(), nullable=True),
    sa.Column('five_day', sa.Float(), nullable=True),
    sa.Column('one_month', sa.Float(), nullable=True),
    sa.Column('three_month', sa.Float(), nullable=True),
    sa.Column('six_month', sa.Float(), nullable=True),
    sa.Column('ytd', sa.Float(), nullable=True),
    sa.Column('one_year', sa.Float(), nullable=True),
    sa.Column('three_year', sa.Float(), nullable=True),
    sa.Column('five_year', sa.Float(), nullable=True),
    sa.Column('ten_year', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_price_change_company')
    )
    op.create_index('ix_price_change_symbol', 'stock_price_changes', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_price_changes_company_id'), 'stock_price_changes', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_price_changes_symbol'), 'stock_price_changes', ['symbol'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_stock_price_company_date')
    )
    op.create_index('ix_stock_price_symbol_date', 'stock_prices', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_stock_prices_company_id'), 'stock_prices', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('portfolio_dividend_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('dividend_per_share', sa.Float(), nullable=False),
    sa.Column('dividend_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', name='currency'), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dividend_amount >= 0', name='check_positive_dividend_amount'),
    sa.CheckConstraint('dividend_per_share >= 0', name='check_positive_dps'),
    sa.CheckConstraint('shares >= 0', name='check_positive_dividend_shares'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_dividend_histories_portfolio_id'), 'portfolio_dividend_histories', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_dividend_histories_symbol'), 'portfolio_dividend_histories', ['symbol'], unique=False)
    op.create_index('ix_portfolio_symbol_payment_date', 'portfolio_dividend_histories', ['portfolio_id', 'symbol', 'payment_date'], unique=False)
    op.create_table('portfolio_holding_performances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', name='currency'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_portfolio_holding')
    )
    op.create_index('ix_holding_portfolio_symbol', 'portfolio_holding_performances', ['portfolio_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_holding_performances_portfolio_id'), 'portfolio_holding_performances', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holding_performances_symbol'), 'portfolio_holding_performances', ['symbol'], unique=False)
    op.create_table('portfolio_trading_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.Enum('BUY', 'SELL', name='tradetype'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', name='currency'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price_per_share', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('net_total', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commission >= 0', name='check_positive_commission'),
    sa.CheckConstraint('fees >= 0', name='check_positive_fees'),
    sa.CheckConstraint('price_per_share >= 0', name='check_positive_price'),
    sa.CheckConstraint('shares > 0', name='check_positive_trade_shares'),
    sa.CheckConstraint('tax >= 0', name='check_positive_tax'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_symbol_trade_date', 'portfolio_trading_histories', ['portfolio_id', 'symbol', 'trade_date'], unique=False)
    op.create_index(op.f('ix_portfolio_trading_histories_portfolio_id'), 'portfolio_trading_histories', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_trading_histories_symbol'), 'portfolio_trading_histories', ['symbol'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_item')
    )
    op.create_index(op.f('ix_watchlist_items_symbol'), 'watchlist_items', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_symbol'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_portfolio_trading_histories_symbol'), table_name='portfolio_trading_histories')
    op.drop_index(op.f('ix_portfolio_trading_histories_portfolio_id'), table_name='portfolio_trading_histories')
    op.drop_index('ix_portfolio_symbol_trade_date', table_name='portfolio_trading_histories')
    op.drop_table('portfolio_trading_histories')
    op.drop_index(op.f('ix_portfolio_holding_performances_symbol'), table_name='portfolio_holding_performances')
    op.drop_index(op.f('ix_portfolio_holding_performances_portfolio_id'), table_name='portfolio_holding_performances')
    op.drop_index('ix_holding_portfolio_symbol', table_name='portfolio_holding_performances')
    op.drop_table('portfolio_holding_performances')
    op.drop_index('ix_portfolio_symbol_payment_date', table_name='portfolio_dividend_histories')
    op.drop_index(op.f('ix_portfolio_dividend_histories_symbol'), table_name='portfolio_dividend_histories')
    op.drop_index(op.f('ix_portfolio_dividend_histories_portfolio_id'), table_name='portfolio_dividend_histories')
    op.drop_table('portfolio_dividend_histories')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_company_id'), table_name='stock_prices')
    op.drop_index('ix_stock_price_symbol_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_stock_price_changes_symbol'), table_name='stock_price_changes')
    op.drop_index(op.f('ix_stock_price_changes_company_id'), table_name='stock_price_changes')
    op.drop_index('ix_price_change_symbol', table_name='stock_price_changes')
    op.drop_table('stock_price_changes')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notification_user_date', table_name='notifications')
    op.drop_index('ix_notification_category', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_technical_indicator_symbol_date', table_name='company_technical_indicators')
    op.drop_index(op.f('ix_company_technical_indicators_symbol'), table_name='company_technical_indicators')
    op.drop_index(op.f('ix_company_technical_indicators_company_id'), table_name='company_technical_indicators')
    op.drop_table('company_technical_indicators')
    op.drop_index('ix_stock_split_symbol_date', table_name='company_stock_splits')
    op.drop_index(op.f('ix_company_stock_splits_symbol'), table_name='company_stock_splits')
    op.drop_index(op.f('ix_company_stock_splits_company_id'), table_name='company_stock_splits')
    op.drop_table('company_stock_splits')
    op.drop_index('ix_stock_peer_symbol', table_name='company_stock_peers')
    op.drop_index(op.f('ix_company_stock_peers_symbol'), table_name='company_stock_peers')
    op.drop_index(op.f('ix_company_stock_peers_company_id'), table_name='company_stock_peers')
    op.drop_table('company_stock_peers')
    op.drop_index('ix_stock_news_symbol_date', table_name='company_stock_news')
    op.drop_index(op.f('ix_company_stock_news_symbol'), table_name='company_stock_news')
    op.drop_index(op.f('ix_company_stock_news_id'), table_name='company_stock_news')
    op.drop_index(op.f('ix_company_stock_news_company_id'), table_name='company_stock_news')
    op.drop_table('company_stock_news')
    op.drop_index('ix_segment_symbol_year', table_name='company_revenue_product_segmentations')
    op.drop_index(op.f('ix_company_revenue_product_segmentations_symbol'), table_name='company_revenue_product_segmentations')
    op.drop_index(op.f('ix_company_revenue_product_segmentations_id'), table_name='company_revenue_product_segmentations')
    op.drop_index(op.f('ix_company_revenue_product_segmentations_company_id'), table_name='company_revenue_product_segmentations')
    op.drop_table('company_revenue_product_segmentations')
    op.drop_index('ix_rating_summary_symbol', table_name='company_rating_summaries')
    op.drop_index(op.f('ix_company_rating_summaries_symbol'), table_name='company_rating_summaries')
    op.drop_index(op.f('ix_company_rating_summaries_id'), table_name='company_rating_summaries')
    op.drop_index(op.f('ix_company_rating_summaries_company_id'), table_name='company_rating_summaries')
    op.drop_table('company_rating_summaries')
    op.drop_index(op.f('ix_company_price_targets_symbol'), table_name='company_price_targets')
    op.drop_index(op.f('ix_company_price_targets_id'), table_name='company_price_targets')
    op.drop_index(op.f('ix_company_price_targets_company_id'), table_name='company_price_targets')
    op.drop_table('company_price_targets')
    op.drop_index('ix_price_target_summary_symbol', table_name='company_price_target_summaries')
    op.drop_index(op.f('ix_company_price_target_summaries_symbol'), table_name='company_price_target_summaries')
    op.drop_index(op.f('ix_company_price_target_summaries_id'), table_name='company_price_target_summaries')
    op.drop_index(op.f('ix_company_price_target_summaries_company_id'), table_name='company_price_target_summaries')
    op.drop_table('company_price_target_summaries')
    op.drop_index('ix_price_target_news_symbol_date', table_name='company_price_target_news')
    op.drop_index(op.f('ix_company_price_target_news_symbol'), table_name='company_price_target_news')
    op.drop_index(op.f('ix_company_price_target_news_id'), table_name='company_price_target_news')
    op.drop_table('company_price_target_news')
    op.drop_index('ix_metrics_symbol_date', table_name='company_key_metrics')
    op.drop_index('ix_metrics_fiscal_year', table_name='company_key_metrics')
    op.drop_index(op.f('ix_company_key_metrics_symbol'), table_name='company_key_metrics')
    op.drop_index(op.f('ix_company_key_metrics_id'), table_name='company_key_metrics')
    op.drop_index(op.f('ix_company_key_metrics_fiscal_year'), table_name='company_key_metrics')
    op.drop_index(op.f('ix_company_key_metrics_company_id'), table_name='company_key_metrics')
    op.drop_table('company_key_metrics')
    op.drop_index('ix_income_symbol_date', table_name='company_income_statements')
    op.drop_index('ix_income_fiscal_year', table_name='company_income_statements')
    op.drop_index(op.f('ix_company_income_statements_symbol'), table_name='company_income_statements')
    op.drop_index(op.f('ix_company_income_statements_id'), table_name='company_income_statements')
    op.drop_index(op.f('ix_company_income_statements_fiscal_year'), table_name='company_income_statements')
    op.drop_index(op.f('ix_company_income_statements_company_id'), table_name='company_income_statements')
    op.drop_table('company_income_statements')
    op.drop_index('ix_grading_symbol_date', table_name='company_gradings')
    op.drop_index(op.f('ix_company_gradings_symbol'), table_name='company_gradings')
    op.drop_index(op.f('ix_company_gradings_id'), table_name='company_gradings')
    op.drop_index(op.f('ix_company_gradings_company_id'), table_name='company_gradings')
    op.drop_table('company_gradings')
    op.drop_index('ix_grading_summary_symbol', table_name='company_grading_summaries')
    op.drop_index(op.f('ix_company_grading_summaries_symbol'), table_name='company_grading_summaries')
    op.drop_index(op.f('ix_company_grading_summaries_id'), table_name='company_grading_summaries')
    op.drop_table('company_grading_summaries')
    op.drop_index('ix_grading_news_symbol_date', table_name='company_grading_news')
    op.drop_index(op.f('ix_company_grading_news_symbol'), table_name='company_grading_news')
    op.drop_index(op.f('ix_company_grading_news_id'), table_name='company_grading_news')
    op.drop_index(op.f('ix_company_grading_news_company_id'), table_name='company_grading_news')
    op.drop_table('company_grading_news')
    op.drop_index('ix_general_news_symbol_date', table_name='company_general_news')
    op.drop_index(op.f('ix_company_general_news_symbol'), table_name='company_general_news')
    op.drop_index(op.f('ix_company_general_news_id'), table_name='company_general_news')
    op.drop_index(op.f('ix_company_general_news_company_id'), table_name='company_general_news')
    op.drop_table('company_general_news')
    op.drop_index('ix_score_symbol', table_name='company_financial_scores')
    op.drop_index(op.f('ix_company_financial_scores_symbol'), table_name='company_financial_scores')
    op.drop_index(op.f('ix_company_financial_scores_id'), table_name='company_financial_scores')
    op.drop_index(op.f('ix_company_financial_scores_company_id'), table_name='company_financial_scores')
    op.drop_table('company_financial_scores')
    op.drop_index('ix_ratio_symbol_date', table_name='company_financial_ratios')
    op.drop_index('ix_ratio_fiscal_year', table_name='company_financial_ratios')
    op.drop_index(op.f('ix_company_financial_ratios_symbol'), table_name='company_financial_ratios')
    op.drop_index(op.f('ix_company_financial_ratios_id'), table_name='company_financial_ratios')
    op.drop_index(op.f('ix_company_financial_ratios_fiscal_year'), table_name='company_financial_ratios')
    op.drop_index(op.f('ix_company_financial_ratios_company_id'), table_name='company_financial_ratios')
    op.drop_table('company_financial_ratios')
    op.drop_index('ix_health_symbol_section', table_name='company_financial_health')
    op.drop_index(op.f('ix_company_financial_health_symbol'), table_name='company_financial_health')
    op.drop_index(op.f('ix_company_financial_health_company_id'), table_name='company_financial_health')
    op.drop_table('company_financial_health')
    op.drop_index('ix_dcf_symbol_date', table_name='company_dcf')
    op.drop_index(op.f('ix_company_dcf_symbol'), table_name='company_dcf')
    op.drop_index(op.f('ix_company_dcf_id'), table_name='company_dcf')
    op.drop_index(op.f('ix_company_dcf_company_id'), table_name='company_dcf')
    op.drop_table('company_dcf')
    op.drop_index(op.f('ix_company_cash_flow_statements_symbol'), table_name='company_cash_flow_statements')
    op.drop_index(op.f('ix_company_cash_flow_statements_fiscal_year'), table_name='company_cash_flow_statements')
    op.drop_index(op.f('ix_company_cash_flow_statements_company_id'), table_name='company_cash_flow_statements')
    op.drop_index('ix_cashflow_symbol_date', table_name='company_cash_flow_statements')
    op.drop_index('ix_cashflow_fiscal_year', table_name='company_cash_flow_statements')
    op.drop_table('company_cash_flow_statements')
    op.drop_index(op.f('ix_company_balance_sheets_symbol'), table_name='company_balance_sheets')
    op.drop_index(op.f('ix_company_balance_sheets_fiscal_year'), table_name='company_balance_sheets')
    op.drop_index(op.f('ix_company_balance_sheets_company_id'), table_name='company_balance_sheets')
    op.drop_index('ix_balance_sheet_symbol_date', table_name='company_balance_sheets')
    op.drop_index('ix_balance_sheet_fiscal_year', table_name='company_balance_sheets')
    op.drop_table('company_balance_sheets')
    op.drop_index('ix_estimate_symbol_date', table_name='company_analyst_estimates')
    op.drop_index(op.f('ix_company_analyst_estimates_symbol'), table_name='company_analyst_estimates')
    op.drop_index(op.f('ix_company_analyst_estimates_id'), table_name='company_analyst_estimates')
    op.drop_index(op.f('ix_company_analyst_estimates_company_id'), table_name='company_analyst_estimates')
    op.drop_table('company_analyst_estimates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_dividend_symbol_date', table_name='company_dividends')
    op.drop_index(op.f('ix_company_dividends_symbol'), table_name='company_dividends')
    op.drop_index(op.f('ix_company_dividends_id'), table_name='company_dividends')
    op.drop_table('company_dividends')
    op.drop_index('ix_company_symbol_exchange', table_name='companies')
    op.drop_index('ix_company_sector_industry', table_name='companies')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_exchange'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
