"""initial migration

Revision ID: 33825db3a822
Revises: 9ae31411a4b5
Create Date: 2025-11-04 22:19:44.976888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33825db3a822'
down_revision: Union[str, Sequence[str], None] = '9ae31411a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_holding_performances', sa.Column('symbol', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_portfolio_holding_performances_holding_symbol'), table_name='portfolio_holding_performances')
    op.drop_index(op.f('ix_holding_portfolio_symbol'), table_name='portfolio_holding_performances')
    op.create_index('ix_holding_portfolio_symbol', 'portfolio_holding_performances', ['portfolio_id', 'symbol'], unique=False)
    op.drop_constraint(op.f('uq_portfolio_holding'), 'portfolio_holding_performances', type_='unique')
    op.create_unique_constraint('uq_portfolio_holding', 'portfolio_holding_performances', ['portfolio_id', 'symbol'])
    op.create_index(op.f('ix_portfolio_holding_performances_symbol'), 'portfolio_holding_performances', ['symbol'], unique=False)
    op.drop_column('portfolio_holding_performances', 'holding_symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_holding_performances', sa.Column('holding_symbol', mysql.VARCHAR(length=20), nullable=False))
    op.drop_index(op.f('ix_portfolio_holding_performances_symbol'), table_name='portfolio_holding_performances')
    op.drop_constraint('uq_portfolio_holding', 'portfolio_holding_performances', type_='unique')
    op.create_unique_constraint(op.f('uq_portfolio_holding'), 'portfolio_holding_performances', ['portfolio_id', 'holding_symbol'])
    op.drop_index('ix_holding_portfolio_symbol', table_name='portfolio_holding_performances')
    op.create_index(op.f('ix_holding_portfolio_symbol'), 'portfolio_holding_performances', ['portfolio_id', 'holding_symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_holding_performances_holding_symbol'), 'portfolio_holding_performances', ['holding_symbol'], unique=False)
    op.drop_column('portfolio_holding_performances', 'symbol')
    # ### end Alembic commands ###
