"""add stock news table

Revision ID: 9af736cba74d
Revises: 891ac1c87558
Create Date: 2025-10-24 23:19:54.573548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af736cba74d'
down_revision: Union[str, Sequence[str], None] = '891ac1c87558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_stock_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('news_title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('news_url', sa.String(length=1000), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_stock_news_company_id'), 'company_stock_news', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_stock_news_id'), 'company_stock_news', ['id'], unique=False)
    op.create_index(op.f('ix_company_stock_news_symbol'), 'company_stock_news', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_stock_news_symbol'), table_name='company_stock_news')
    op.drop_index(op.f('ix_company_stock_news_id'), table_name='company_stock_news')
    op.drop_index(op.f('ix_company_stock_news_company_id'), table_name='company_stock_news')
    op.drop_table('company_stock_news')
    # ### end Alembic commands ###
