"""Initia

Revision ID: e5e34517877b
Revises: 606bc7a1fcc5
Create Date: 2025-11-08 16:52:23.428060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e34517877b'
down_revision: Union[str, Sequence[str], None] = '606bc7a1fcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_dividends', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_dividends', 'currency')
    # ### end Alembic commands ###
