"""add health table

Revision ID: fb62cf444e08
Revises: a1f6686414e3
Create Date: 2025-10-27 23:45:14.354362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb62cf444e08'
down_revision: Union[str, Sequence[str], None] = 'a1f6686414e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_stock_peers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('company_stock_peers', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_stock_peers', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('company_stock_peers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
